# Settings for size
BUF_LEN = 1024
JOURNAL_CUT_LIMIT = (1024 ** 2) * 64  # 64MB
# Settings for timing
VOTE_CYCLE = 0.5  # 200ms
PING_CYCLE = 0.05  # 100ms
ELECTION_TIMEOUT = 0.5  # 400ms
TICK_CYCLE = 0.002  # 5ms

# Settings for internal queue
MAX_BATCH_ITEMS = 200  # This number has NOT been optimized!

# Settings for log naming
SNAPSHOT_FILE_NAME_PREFIX = 'stm_snapshot'
JOURNAL_PREFIX = 'eventlet_raft_journal'

# Define roles
ROLE_MEMBER = 0
ROLE_CANDIDATE = 1
ROLE_LEADER = 2

# Define message type
MSG_TYPE_VOTE_REQ = 0
MSG_TYPE_VOTE_RET = 1
MSG_TYPE_LOG_ENTRY_APPEND_REQ = 2
MSG_TYPE_LOG_ENTRY_APPEND_RET = 3
MSG_TYPE_CLIENT_REGISTER_REQ = 4
MSG_TYPE_CLIENT_REGISTER_RET = 5
MSG_TYPE_CLIENT_UPDATE_REQ = 6
MSG_TYPE_CLIENT_UPDATE_RET = 7
MSG_TYPE_CLIENT_QUERY_REQ = 8
MSG_TYPE_CLIENT_QUERY_RET = 9
MSG_TYPE_TERM_INIT = 10

# Define operations
STM_OP_INT = 100
STM_OP_REG = 101
STM_OP_SET = 102
STM_OP_DEL = 103
STM_OP_GET = 104

# Define log type
LOG_TYPE_CLIENT_REG = 200
LOG_TYPE_CLIENT_REQ = 201
LOG_TYPE_SERVER_CMT = 202
LOG_TYPE_CANCEL_IDX = 203
LOG_TYPE_COMMIT_CHG = 204

# Define stm response code
STM_RET_CODE_OK = 500
STM_RET_CODE_ERROR = 501

# STM response code extension for key-value STM.
STM_RET_CODE_ERROR_EXT_KEY_ERROR = 600
