BUF_LEN = 1024
VOTE_CYCLE = 0.2  # 200ms
PING_CYCLE = 0.1  # 100ms
ELECTION_TIMEOUT = 0.4  # 400ms
TICK_CYCLE = 0.005  # 5ms

SNAPSHOT_FILE_NAME_PREFIX = 'stm_snapshot'
JOURNAL_PREFIX = 'eventlet_raft_journal'

ROLE_MEMBER = 0
ROLE_CANDIDATE = 1
ROLE_LEADER = 2

STM_OP_SET = 0
STM_OP_DEL = 1
